In [1]:
import random
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline 
import warnings
warnings.filterwarnings("ignore")

In [2]:
# load the dataset
df = pd.read_csv('FODS-A2.csv')
df.head()

,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,...,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2,Appliances
0,21.20,33.290,19.823333,31.790000,23.463333,38.230000,20.50,31.73,19.200000,39.363333,...,29.230000,9.85,756.183333,41.833333,4.833333,40.0,-2.67,42.017180,42.017180,290
1,21.79,38.500,19.500000,40.633333,22.500000,37.900000,21.00,37.90,20.033333,47.290000,...,40.326667,6.90,754.000000,75.000000,4.000000,40.0,2.80,24.624380,24.624380,50
2,22.39,41.390,20.200000,43.790000,24.500000,39.333333,20.10,38.26,19.390000,48.090000,...,42.060000,10.10,756.433333,68.000000,5.833333,40.0,4.45,3.731260,3.731260,260
3,24.00,30.260,24.390000,26.963333,23.390000,33.400000,22.79,31.20,21.033333,40.626667,...,35.500000,19.10,760.000000,31.000000,4.000000,40.0,1.50,1.058826,1.058826,50
4,20.05,38.245,17.600000,41.000000,21.100000,37.200000,19.89,36.40,18.200000,43.560000,...,38.863333,0.10,754.600000,99.000000,1.000000,32.0,-0.10,39.248108,39.248108,30

In [3]:
df.isnull().sum()#any missing values in column

T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
Appliances     0
dtype: int64

In [4]:
df[df.isnull().any(axis=1)]# any missing values in row

Empty DataFrame
Columns: [T1, RH_1, T2, RH_2, T3, RH_3, T4, RH_4, T5, RH_5, T6, RH_6, T7, RH_7, T8, RH_8, T9, RH_9, T_out, Press_mm_hg, RH_out, Windspeed, Visibility, Tdewpoint, rv1, rv2, Appliances]
Index: []

[0 rows x 27 columns]

In [5]:
X=df.iloc[:,0:26]
y=df.iloc[:,-1]

In [6]:
order = list(range(len(y)))

shuffle = random.sample(order, int(len(order) * 0.8))

rem = [i for i in order if i not in shuffle]

In [7]:
# train test split
X_train = X.iloc[shuffle,:]
y_train = y.iloc[shuffle]
X_test = X.iloc[rem,:]
y_test = y.iloc[rem]

In [8]:
X_train.shape

(6315, 26)

In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

def forward_feature_selection():
    # forward feature selection
    selected = []
    remaining = list(X_train.columns)
    best_new_score = 0.0
    while remaining :
        scores_with_candidates = []
        for candidate in remaining:
            X_train_selected = X_train[selected + [candidate]]
            # calculate rmse score
            score = LinearRegression()
            scores_with_candidates.append((score, candidate))
        # scores_with_candidates.sort(reverse=True)
        # print(scores_with_candidates)
        best_new_score, best_candidate = scores_with_candidates.pop()
        remaining.remove(best_candidate)
        selected.append(best_candidate)
        print('selected =', selected)
        print('remaining =', remaining)
    return selected

In [10]:
selected = forward_feature_selection()
selected

selected = ['rv2']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility', 'Tdewpoint', 'rv1']
selected = ['rv2', 'rv1']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility', 'Tdewpoint']
selected = ['rv2', 'rv1', 'Tdewpoint']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'T_out']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9', 'T9']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9', 'T9', 'RH_8']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9', 'T9', 'RH_8', 'T8']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9', 'T9', 'RH_8', 'T8', 'RH_7']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9', 'T9', 'RH_8', 'T8', 'RH_7', 'T7']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9', 'T9', 'RH_8', 'T8', 'RH_7', 'T7', 'RH_6']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9', 'T9', 'RH_8', 'T8', 'RH_7', 'T7', 'RH_6', 'T6']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9', 'T9', 'RH_8', 'T8', 'RH_7', 'T7', 'RH_6', 'T6', 'RH_5']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9', 'T9', 'RH_8', 'T8', 'RH_7', 'T7', 'RH_6', 'T6', 'RH_5', 'T5']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9', 'T9', 'RH_8', 'T8', 'RH_7', 'T7', 'RH_6', 'T6', 'RH_5', 'T5', 'RH_4']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9', 'T9', 'RH_8', 'T8', 'RH_7', 'T7', 'RH_6', 'T6', 'RH_5', 'T5', 'RH_4', 'T4']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9', 'T9', 'RH_8', 'T8', 'RH_7', 'T7', 'RH_6', 'T6', 'RH_5', 'T5', 'RH_4', 'T4', 'RH_3']
remaining = ['T1', 'RH_1', 'T2', 'RH_2', 'T3']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9', 'T9', 'RH_8', 'T8', 'RH_7', 'T7', 'RH_6', 'T6', 'RH_5', 'T5', 'RH_4', 'T4', 'RH_3', 'T3']
remaining = ['T1', 'RH_1', 'T2', 'RH_2']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9', 'T9', 'RH_8', 'T8', 'RH_7', 'T7', 'RH_6', 'T6', 'RH_5', 'T5', 'RH_4', 'T4', 'RH_3', 'T3', 'RH_2']
remaining = ['T1', 'RH_1', 'T2']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9', 'T9', 'RH_8', 'T8', 'RH_7', 'T7', 'RH_6', 'T6', 'RH_5', 'T5', 'RH_4', 'T4', 'RH_3', 'T3', 'RH_2', 'T2']
remaining = ['T1', 'RH_1']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9', 'T9', 'RH_8', 'T8', 'RH_7', 'T7', 'RH_6', 'T6', 'RH_5', 'T5', 'RH_4', 'T4', 'RH_3', 'T3', 'RH_2', 'T2', 'RH_1']
remaining = ['T1']
selected = ['rv2', 'rv1', 'Tdewpoint', 'Visibility', 'Windspeed', 'RH_out', 'Press_mm_hg', 'T_out', 'RH_9', 'T9', 'RH_8', 'T8', 'RH_7', 'T7', 'RH_6', 'T6', 'RH_5', 'T5', 'RH_4', 'T4', 'RH_3', 'T3', 'RH_2', 'T2', 'RH_1', 'T1']
remaining = []

['rv2',
 'rv1',
 'Tdewpoint',
 'Visibility',
 'Windspeed',
 'RH_out',
 'Press_mm_hg',
 'T_out',
 'RH_9',
 'T9',
 'RH_8',
 'T8',
 'RH_7',
 'T7',
 'RH_6',
 'T6',
 'RH_5',
 'T5',
 'RH_4',
 'T4',
 'RH_3',
 'T3',
 'RH_2',
 'T2',
 'RH_1',
 'T1']

In [1]:
import pandas as pd
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.linear_model import LinearRegression
import numpy as np

df = pd.read_csv('FODS-A2.csv')
# normalize

X=df.iloc[:,0:26]
y=df.iloc[:,-1]
#min max normalize
X_max=X.max()
X_min=X.min()
X=(X-X_min)/(X_max-X_min)
y_max=y.max()
y_min=y.min()
y=(y-y_min)/(y_max-y_min)

sfs = SFS(LinearRegression(),
           k_features=26,
           forward=True,
           floating=False,
           cv = 0)
#Use SFS to select the top 5 features 
sfs.fit(X, y)

#Create a dataframe for the SFS results 
df_SFS_results = pd.DataFrame(sfs.subsets_).transpose()
df_SFS_results

,feature_idx,cv_scores,avg_score,feature_names
1,"(20,)",[0.02492863337748963],0.024929,"(RH_out,)"
2,"(1, 20)",[0.04070763638208186],0.040708,"(RH_1, RH_out)"
3,"(1, 13, 20)",[0.06664180532626196],0.066642,"(RH_1, RH_7, RH_out)"
4,"(1, 3, 13, 20)",[0.08238481150235],0.082385,"(RH_1, RH_2, RH_7, RH_out)"
5,"(1, 3, 13, 15, 20)",[0.08710387633113204],0.087104,"(RH_1, RH_2, RH_7, RH_8, RH_out)"
6,"(1, 3, 13, 15, 20, 21)",[0.09149201961080111],0.091492,"(RH_1, RH_2, RH_7, RH_8, RH_out, Windspeed)"
7,"(1, 3, 13, 15, 16, 20, 21)",[0.09362676185710572],0.093627,"(RH_1, RH_2, RH_7, RH_8, T9, RH_out, Windspeed)"
8,"(1, 3, 4, 13, 15, 16, 20, 21)",[0.1204255681402091],0.120426,"(RH_1, RH_2, T3, RH_7, RH_8, T9, RH_out, Winds..."
9,"(1, 2, 3, 4, 13, 15, 16, 20, 21)",[0.12634580717852917],0.126346,"(RH_1, T2, RH_2, T3, RH_7, RH_8, T9, RH_out, W..."
10,"(1, 2, 3, 4, 13, 14, 15, 16, 20, 21)",[0.13077899835046924],0.130779,"(RH_1, T2, RH_2, T3, RH_7, T8, RH_8, T9, RH_ou..."
11,"(1, 2, 3, 4, 10, 13, 14, 15, 16, 20, 21)",[0.13368130388980715],0.133681,"(RH_1, T2, RH_2, T3, T6, RH_7, T8, RH_8, T9, R..."
12,"(1, 2, 3, 4, 5, 10, 13, 14, 15, 16, 20, 21)",[0.13564754421846148],0.135648,"(RH_1, T2, RH_2, T3, RH_3, T6, RH_7, T8, RH_8,..."
13,"(1, 2, 3, 4, 5, 10, 13, 14, 15, 16, 18, 20, 21)",[0.13747231407579108],0.137472,"(RH_1, T2, RH_2, T3, RH_3, T6, RH_7, T8, RH_8,..."
14,"(1, 2, 3, 4, 5, 10, 11, 13, 14, 15, 16, 18, 20...",[0.1382883888676827],0.138288,"(RH_1, T2, RH_2, T3, RH_3, T6, RH_6, RH_7, T8,..."
15,"(1, 2, 3, 4, 5, 9, 10, 11, 13, 14, 15, 16, 18,...",[0.13912822066566],0.139128,"(RH_1, T2, RH_2, T3, RH_3, RH_5, T6, RH_6, RH_..."
16,"(1, 2, 3, 4, 5, 6, 9, 10, 11, 13, 14, 15, 16, ...",[0.1398804760442609],0.13988,"(RH_1, T2, RH_2, T3, RH_3, T4, RH_5, T6, RH_6,..."
17,"(1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 14, 15, 1...",[0.14089228956150412],0.140892,"(RH_1, T2, RH_2, T3, RH_3, T4, RH_4, RH_5, T6,..."
18,"(1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 14, 15, 1...",[0.14118465304611494],0.141185,"(RH_1, T2, RH_2, T3, RH_3, T4, RH_4, RH_5, T6,..."
19,"(1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 14, 15, 1...",[0.14145853579371914],0.141459,"(RH_1, T2, RH_2, T3, RH_3, T4, RH_4, RH_5, T6,..."
20,"(1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 14, 15, 1...",[0.14160270882378556],0.141603,"(RH_1, T2, RH_2, T3, RH_3, T4, RH_4, RH_5, T6,..."
21,"(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15...",[0.14169805026835536],0.141698,"(RH_1, T2, RH_2, T3, RH_3, T4, RH_4, T5, RH_5,..."
22,"(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15...",[0.14176180488512202],0.141762,"(RH_1, T2, RH_2, T3, RH_3, T4, RH_4, T5, RH_5,..."
23,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14,...",[0.14179739934750446],0.141797,"(T1, RH_1, T2, RH_2, T3, RH_3, T4, RH_4, T5, R..."
24,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",[0.14180802200213516],0.141808,"(T1, RH_1, T2, RH_2, T3, RH_3, T4, RH_4, T5, R..."
25,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",[0.1418127672068593],0.141813,"(T1, RH_1, T2, RH_2, T3, RH_3, T4, RH_4, T5, R..."
26,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",[0.1418127672068593],0.141813,"(T1, RH_1, T2, RH_2, T3, RH_3, T4, RH_4, T5, R..."

In [10]:
from mlxtend.feature_selection import SequentialFeatureSelector as sfs
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np

df = pd.read_csv('FODS-A2.csv')
lreg = LinearRegression()
X=df.iloc[:,0:26]
y=df.iloc[:,-1]
sfs1 = sfs(lreg, k_features=1, forward=False, verbose=1, scoring='neg_mean_squared_error')
sfs1 = sfs1.fit(X, y)
feat_names = list(sfs1.k_feature_names_)
print(feat_names)
new_data = df[feat_names]

df_SFS_results = pd.DataFrame(sfs1.subsets_).transpose()
df_SFS_results

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  26 out of  26 | elapsed:   14.3s finished
Features: 25/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  25 out of  25 | elapsed:    4.1s finished
Features: 24/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  24 out of  24 | elapsed:    4.0s finished
Features: 23/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  23 out of  23 | elapsed:    6.7s finished
Features: 22/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  22 out of  22 | elapsed:    2.9s finished
Features: 21/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  21 out of  21 | elapsed:    3.6s finished
Features: 20/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:    4.7s finished
Features: 19/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  19 out of  19 | elapsed:    2.9s finished
Features: 18/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  18 out of  18 | elapsed:    2.0s finished
Features: 17/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  17 out of  17 | elapsed:    1.7s finished
Features: 16/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  16 out of  16 | elapsed:    1.7s finished
Features: 15/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  15 out of  15 | elapsed:    1.3s finished
Features: 14/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  14 out of  14 | elapsed:    1.0s finished
Features: 13/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  13 out of  13 | elapsed:    0.9s finished
Features: 12/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    0.7s finished
Features: 11/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  11 out of  11 | elapsed:    0.6s finished
Features: 10/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.5s finished
Features: 9/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    0.4s finished
Features: 8/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    0.3s finished
Features: 7/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    0.3s finished
Features: 6/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    0.2s finished
Features: 5/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.1s finished
Features: 4/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.1s finished
Features: 3/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s finished
Features: 2/1[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s finished
Features: 1/1

['RH_8']

,feature_idx,cv_scores,avg_score,feature_names
26,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[-10488.830527917247, -9955.636489099476, -911...",-9425.971349,"(T1, RH_1, T2, RH_2, T3, RH_3, T4, RH_4, T5, R..."
25,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[-10477.89066361995, -9951.74439042043, -9114....",-9421.184233,"(T1, RH_1, T2, RH_2, T3, RH_3, T4, RH_4, T5, R..."
24,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[-10455.058938820472, -9955.093911693024, -911...",-9416.910601,"(T1, RH_1, T2, RH_2, T3, RH_3, T4, RH_4, T5, R..."
23,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14,...","[-10457.621601525718, -9954.359540872789, -911...",-9415.644602,"(T1, RH_1, T2, RH_2, T3, RH_3, T4, RH_4, T5, R..."
22,"(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15...","[-10453.76039163855, -9948.174850522017, -9111...",-9414.396228,"(RH_1, T2, RH_2, T3, RH_3, T4, RH_4, T5, RH_5,..."
21,"(1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 14, 15, 1...","[-10448.745939071076, -9949.539737780053, -911...",-9413.12281,"(RH_1, T2, RH_2, T3, RH_3, T4, RH_4, RH_5, T6,..."
20,"(1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 14, 15, 1...","[-10448.745939071077, -9949.539737780055, -911...",-9413.043558,"(RH_1, T2, RH_2, T3, RH_3, T4, RH_4, RH_5, T6,..."
19,"(1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 14, 15, 1...","[-10437.786811107559, -9951.421753977322, -911...",-9412.022285,"(RH_1, T2, RH_2, T3, RH_3, T4, RH_4, RH_5, T6,..."
18,"(1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 14, 15, 1...","[-10431.404864557027, -9955.872870095318, -911...",-9411.965057,"(RH_1, T2, RH_2, T3, RH_3, T4, RH_4, RH_5, T6,..."
17,"(1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 14, 15, 1...","[-10431.08385434247, -9949.652653613563, -9118...",-9410.606608,"(RH_1, T2, RH_2, T3, RH_3, T4, RH_4, RH_5, T6,..."
16,"(1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 14, 15, 1...","[-10436.646848893359, -9955.62332697694, -9106...",-9412.654778,"(RH_1, T2, RH_2, T3, RH_3, T4, RH_4, RH_5, T6,..."
15,"(1, 2, 3, 4, 5, 6, 7, 10, 11, 13, 14, 15, 16, ...","[-10442.528359610367, -9948.643885517602, -912...",-9415.379512,"(RH_1, T2, RH_2, T3, RH_3, T4, RH_4, T6, RH_6,..."
14,"(1, 2, 3, 4, 5, 7, 10, 11, 13, 14, 15, 16, 18,...","[-10461.041029362188, -9980.451477514736, -915...",-9423.174403,"(RH_1, T2, RH_2, T3, RH_3, RH_4, T6, RH_6, RH_..."
13,"(1, 2, 3, 4, 5, 10, 11, 13, 14, 15, 16, 18, 21)","[-10454.193410125172, -9989.08422211972, -9158...",-9426.361576,"(RH_1, T2, RH_2, T3, RH_3, T6, RH_6, RH_7, T8,..."
12,"(1, 2, 3, 4, 5, 10, 11, 14, 15, 16, 18, 21)","[-10468.220624582824, -10004.144321809865, -91...",-9434.871354,"(RH_1, T2, RH_2, T3, RH_3, T6, RH_6, T8, RH_8,..."
11,"(1, 2, 3, 4, 5, 10, 14, 15, 16, 18, 21)","[-10482.30551311777, -9995.76810447695, -9193....",-9441.738277,"(RH_1, T2, RH_2, T3, RH_3, T6, T8, RH_8, T9, T..."
10,"(1, 2, 3, 4, 10, 14, 15, 16, 18, 21)","[-10493.930888031282, -10025.346618552647, -92...",-9455.594499,"(RH_1, T2, RH_2, T3, T6, T8, RH_8, T9, T_out, ..."
9,"(1, 2, 3, 4, 10, 14, 15, 16, 18)","[-10526.680874418842, -10053.930789115793, -92...",-9475.078004,"(RH_1, T2, RH_2, T3, T6, T8, RH_8, T9, T_out)"
8,"(1, 2, 3, 4, 10, 14, 15, 16)","[-10581.726306964734, -10062.46481869101, -927...",-9493.48952,"(RH_1, T2, RH_2, T3, T6, T8, RH_8, T9)"
7,"(1, 2, 3, 4, 14, 15, 16)","[-10631.031155173243, -10094.768125127137, -92...",-9528.182651,"(RH_1, T2, RH_2, T3, T8, RH_8, T9)"
6,"(1, 2, 3, 4, 15, 16)","[-10706.68478262859, -10171.528063598453, -935...",-9580.551403,"(RH_1, T2, RH_2, T3, RH_8, T9)"
5,"(1, 3, 4, 15, 16)","[-10828.521964570828, -10258.81575578045, -948...",-9674.224568,"(RH_1, RH_2, T3, RH_8, T9)"
4,"(1, 4, 15, 16)","[-11108.509447443095, -10438.431489825087, -96...",-9868.588366,"(RH_1, T3, RH_8, T9)"
3,"(1, 15, 16)","[-11206.285036963887, -10895.38464316538, -987...",-10245.828934,"(RH_1, RH_8, T9)"
2,"(1, 15)","[-11272.429201459778, -10903.486479960782, -10...",-10294.680846,"(RH_1, RH_8)"
1,"(15,)","[-11802.622166263594, -11534.494661921353, -10...",-10801.317614,"(RH_8,)"